Added 2FA Support
Vonage/vonage-ruby-sdk pull request #118
Opened 2019-02-08 18:29 UTC by dusty

2019-02-12 10:32 UTC, timcraft requested changes
Thanks! Looks good overall, just a couple of small details that need adding/tweaking.

2019-02-12 10:32 UTC, timcraft commented on README.md
> +Docs: [https://developer.nexmo.com/api/sms/us-short-codes/2fa](https://developer.nexmo.com/api/sms/us-short-codes/2fa?utm_source=DEV_REL&utm_medium=github&utm_campaign=ruby-client-library#send-a-2fa-
There doesn't appear to be a send-a-2fa-token anchor on that page.

I'd suggest just linking to the page instead.

2019-02-12 10:32 UTC, timcraft commented on lib/nexmo/client.rb
> +    def tfa
This method needs a corresponding test adding to `test/nexmo/client_test.rb`

2019-02-12 10:32 UTC, timcraft commented on lib/nexmo/tfa.rb
> +      request('/sc/us/2fa/json', params: params, type: Post)
This will work for most cases but for completeness it would be good to handle the client-ref parameter. If you look at `sms.rb` and `sms_test.rb` you can see how to handle this—include the Keys module and call `hyphenate(params)` to transform the keys. This allows the caller to use syntax like `client_ref: ...` instead of hashrocket syntax.

2019-02-14 14:36 UTC, dusty commented
The requested changes are complete.  What do you think?  Look good now?

Thanks

2019-02-15 10:30 UTC, timcraft commented
@dusty Looks good, thanks! I'll get this integrated into the next release.

2019-03-01 09:55 UTC, timcraft commented
Merged this manually to fix the README link (trailing parenthesis was missing).

@dusty Available in v5.6.0, thanks for the contribution! 🙏

2019-03-01 09:55 UTC, closed without merging