Add support for Coveralls reporting
Vonage/vonage-ruby-sdk pull request #125
Opened 2019-06-27 08:30 UTC by benhayehudi

Adding Coveralls reporting coverage to the gem

2019-06-27 09:51 UTC, benhayehudi commented
@timcraft - Any idea why the jruby builds continue to fail until I go in manually and restart the builds? It looks like it's failing on the downloads.

2019-06-27 15:05 UTC, benhayehudi commented
> @timcraft - Any idea why the jruby builds continue to fail until I go in manually and restart the builds? It looks like it's failing on the downloads.

This seems to be a new issue with jruby, and not with us, as @fabianrbz discovered, FYI.

2019-06-27 16:22 UTC, timcraft commented
> Any idea why the jruby builds continue to fail until I go in manually and restart the builds? It looks like it's failing on the downloads.

I noticed it before but no idea. The call that is failing is `rvm get stable` so even though it's only on the jruby builds I don't think it's a jruby issue. Whether it's an rvm issue, a travis issue, or an issue with the travis config file we're using I'm not sure 🤷‍♂️

2019-06-28 10:52 UTC, fabianrbz requested changes
@benhayehudi looks good! although i left a comment about the branch, it should point to master right?

2019-06-28 10:52 UTC, fabianrbz commented on README.md
> +[![Gem Version](https://badge.fury.io/rb/nexmo.svg)](https://badge.fury.io/rb/nexmo) [![Build Status](https://api.travis-ci.org/Nexmo/nexmo-ruby.svg?branch=master)](https://travis-ci.org/Nexmo/nexmo-
is there a way to pick up the current branch? if not we should change it to master.

2019-06-28 11:33 UTC, benhayehudi commented on README.md
> +[![Gem Version](https://badge.fury.io/rb/nexmo.svg)](https://badge.fury.io/rb/nexmo) [![Build Status](https://api.travis-ci.org/Nexmo/nexmo-ruby.svg?branch=master)](https://travis-ci.org/Nexmo/nexmo-
Yes, good catch.

2019-06-28 11:51 UTC, merged