Conversations beta-3
Vonage/vonage-ruby-sdk pull request #132
Opened 2019-10-23 08:30 UTC by benhayehudi

**Do not merge this PR until API is in production**

This refactors the existing `Conversation` class of methods for the newest iteration of the Conversation API.

2019-10-23 10:23 UTC, timcraft requested changes
Please don't update CHANGES.md or version.rb as part of a feature change, those are updated as part of the release process. Added some other comments inline.

2019-10-23 10:23 UTC, timcraft commented on lib/nexmo/conversations.rb
> +    self.request_headers['Content-Type'] = 'application/json'
This line should be removed. The Content-Type header shouldn't be set for all requests, and it's already set for requests with JSON bodies automatically.

2019-10-23 10:23 UTC, timcraft commented on lib/nexmo/conversations.rb
> +    #   - **:custom_data** [Hash] Any custom data that you'd like to attach to the conversation.
Please use regular parentheses instead of square brackets for these keys, to be consistent with the existing formatting. For example: `**:custom_data** (Hash)`

2019-10-23 10:23 UTC, timcraft commented on lib/nexmo/conversations.rb
> +    # @option params [None] :cursor
I don't think this is the correct type for the cursor option?

2019-10-23 10:23 UTC, timcraft commented on lib/nexmo/conversations/members.rb
> +    #   The action to take when adding a user to the conversation.
Minor but please add a blank line between the last `@option` and first `@param`, for consistency/readability.

2019-10-23 10:23 UTC, timcraft commented on test/nexmo/conversations_test.rb
> +  def test_create_method_with_error
Error handling is tested separately so this isn't necessary. If there's an error response that's not being caught feel free to open an issue with details and I'll take a look.

2019-10-23 10:57 UTC, benhayehudi commented on lib/nexmo/conversations.rb
> +    self.request_headers['Content-Type'] = 'application/json'
Can you share a link to the release process for edification? Thanks.

2019-10-23 10:57 UTC, benhayehudi commented
> Please don't update CHANGES.md or version.rb as part of a feature change, those are updated as part of the release process. Added some other comments inline.

Can you share a link to the release process for edification and future work? Thanks.

2019-10-23 10:58 UTC, benhayehudi commented on test/nexmo/conversations_test.rb
> +  def test_create_method_with_error
@mheap - These error handling tests were added on your request, would appreciate your input. Thank you.

2019-10-23 10:59 UTC, benhayehudi commented on lib/nexmo/conversations.rb
> +    self.request_headers['Content-Type'] = 'application/json'
👍

2019-10-23 11:00 UTC, benhayehudi commented on lib/nexmo/conversations.rb
> +    #   - **:custom_data** [Hash] Any custom data that you'd like to attach to the conversation.
👍

2019-10-23 11:01 UTC, benhayehudi commented on lib/nexmo/conversations.rb
> +    # @option params [None] :cursor
Yes, good catch.

2019-10-23 11:02 UTC, benhayehudi commented on lib/nexmo/conversations/members.rb
> +    #   The action to take when adding a user to the conversation.
👍

2019-10-23 11:35 UTC, timcraft commented
> Can you share a link to the release process for edification and future work?

I don't think the release process for any of the SDKs is documented?

Workflows vary, but I'd say it was fairly standard practice not to mix up release related changes with development changes—helps keep things separate and easier to organize/review/manage.

2019-10-23 12:54 UTC, mheap commented
Hey Tim!

We're working on getting things like the release process documented, so if there's a specific set of actions that you've been doing it'd be great to see those so that we're all on the same page. Could you please create a `RELEASE.md` for `nexmo-ruby`?

2019-10-23 12:56 UTC, mheap commented on test/nexmo/conversations_test.rb
> +  def test_create_method_with_error
The HTTP client may check for errors, but without a failure case test we have no guarantees that the conversations related functionality is following the code path that handles errors.

Stubbing out a 400 response and expecting a specific exception to be thrown feels like the correct balance of sanity checking and detail to me

2019-10-23 14:25 UTC, timcraft commented
> Could you please create a `RELEASE.md` for `nexmo-ruby`?

Sure, is there a template I can use? Something similar to the MAINTENANCE.md in nexmo-node?

2019-10-23 14:26 UTC, timcraft commented on test/nexmo/conversations_test.rb
> +  def test_create_method_with_error
Makes sense but surely that applies to all endpoints, and to apply that consistently would need an additional failure case test per endpoint? All the endpoints use the same codepath by design, and the errors are tested separately so as to eliminate the need to test them per endpoint (and ultimately make it easier to add new functionality).

2019-10-25 08:17 UTC, mheap commented
@timcraft Yep, something similar to that would be great

2019-10-25 08:19 UTC, mheap commented on test/nexmo/conversations_test.rb
> +  def test_create_method_with_error
Yep, this applies to all endpoints not just the conversation endpoints.

Adding tests at this level may be duplication, but we've seen them deliver value in other languages. A single error test case for each API provides enough reassurance with minimal investment that I think it's worth it

2020-02-24 17:28 UTC, timcraft commented
Closing this for now—suggest we restart a fresh PR when the API changes are in production.

2020-02-28 13:49 UTC, dragonmantank commented
Reopening, this needs to stay open for visibility.

2021-03-04 08:28 UTC, closed without merging