Introduce all Nexmo signing hashing options to Signature
Vonage/vonage-ruby-sdk pull request #134
Opened 2019-10-28 10:01 UTC by benhayehudi

This PR brings the Ruby SDK into conformity with the API requirement of allowing for multiple hashing options (https://developer.nexmo.com/concepts/guides/signing-messages), specifically: `md5`, `md5hash`, `sha1`, `sha256` and `sha512`. It does this by refactoring to use the built in `OpenSSL` functionality instead of the `Digest` gem, which does not have MD5 HMAC capabilities. New tests are introduced to verify each signature hashing option. The final message for an invalid option in the `case` statement is in line with the messaging offered in parallel SDKs (i.e. https://github.com/Nexmo/nexmo-php/blob/master/src/Client/Signature.php#L59-L72), as is the code structure.

2019-10-28 11:35 UTC, mheap commented on lib/nexmo/signature.rb
> +    def check(signature_method, params)
This would be a breaking change. Can we make the signature `(params, signature_method='md5hash'`)?

2019-10-28 12:11 UTC, benhayehudi commented on lib/nexmo/signature.rb
> +    def check(signature_method, params)
Yes, absolutely.

2019-10-30 05:53 UTC, benhayehudi commented
Hi @timcraft!

Can you please review this when you get a moment? Also, what's the ETA for a `release.md` to guide this and future releases? 

Thanks,

Ben

2019-10-30 12:39 UTC, timcraft requested changes
Added some review comments inline.

2019-10-30 12:39 UTC, timcraft commented on lib/nexmo/signature.rb
> -require 'digest/md5'
This should be replaced with `require 'openssl'` to make sure OpenSSL is loaded

2019-10-30 12:39 UTC, timcraft commented on lib/nexmo/signature.rb
> -
Not clear why this blank line was removed?

2019-10-30 12:39 UTC, timcraft commented on lib/nexmo/signature.rb
> +    def check(signature_method = 'md5hash', params)
As @mheap already pointed out this change to the method signature is backwards incompatible, and it makes no sense to be releasing a v7 so soon after v6.

Can you change it to a keyword argument after the params instead?

2019-10-30 12:39 UTC, timcraft commented on lib/nexmo/signature.rb
> +        hash = OpenSSL::Digest::MD5.new
Using `hash` as a variable name is a bit confusing, given Ruby's `Hash` class

Suggest using `digest` instead, as per the [OpenSSL::Digest docs](https://docs.ruby-lang.org/en/2.5.0/OpenSSL/Digest.html)

2019-10-30 12:39 UTC, timcraft commented on lib/nexmo/signature.rb
> +      if signature_method == 'md5'
Looking at the NDP guide and the nexmo-php code I'm not sure the algorithm is implemented correctly here

2019-10-30 12:39 UTC, timcraft commented on test/nexmo/signature_test.rb
> +    assert_equal('Unknown signature algorithm: xxxx. Expected: md5hash, md5, sha1, sha256, or sha512.', exception.message)
Please can you remove the brackets/parentheses from the `assert_equal` call for consistency

(Generally speaking it's best to format new code to be consistent with existing code)

2019-10-30 12:43 UTC, timcraft commented
> Can you please review this when you get a moment? Also, what's the ETA for a `release.md` to guide this and future releases?

Initial review done. As soon as I get chance to write it up, but the salient points are new features should be merged into `develop`, and that is then merged into `master` as part of the release process. This is the established workflow that is documented briefly [here](https://github.com/Nexmo/client-library-specification#workflow).

2019-11-05 12:53 UTC, benhayehudi commented
I have changed the branch to merge into to `develop` from `master`, I believe which is in accordance with the release process. Does that seem correct? Thanks so much.

2019-11-05 14:21 UTC, timcraft commented
> I have changed the branch to merge into to `develop` from `master`, I believe which is in accordance with the release process. Does that seem correct? Thanks so much.

That's correct, thanks 👍

The blocker on this currently is the new logic for generating the signature, which AFAICT is incorrect. Once you're happy the new logic is correct I'd suggest pinging myself and @mheap for another review. It's not enough for "tests are passing" on something like this because it's too easy to just paste in the hashes that are being returned. Then I can merge it into develop with some other stuff I'm working on, and include in the next release.

2019-11-05 14:21 UTC, timcraft commented
@mheap Regarding workflows, are you able to change the default branch in settings?

2019-11-05 16:20 UTC, lornajane commented
@timcraft Michael's out of the office this week but I can change the repo settings if that would be helpful? It looks like the default branch is `master` so I'm not sure what is needed here

2019-11-05 21:56 UTC, dragonmantank requested changes

2019-11-05 21:56 UTC, dragonmantank commented on lib/nexmo/signature.rb
> +      if signature_method == 'md5'
Yeah, there are a few little issues that are keeping this from working with values we expect. BTW, I updated https://github.com/Nexmo/nexmo-php/blob/master/test/Client/SignatureTest.php to have better tests with all the hashes, so you could copy over the passed objects and hashes to test against.

Instead of updating the digest, it's probably easier to just concat a string to build up our data we want to check. `params.sort` is sorting correctly, but instead of dumping it into a digest I would just dump it into a string, which makes the next suggestion easier.

I believe you should be able to just use `OpenSSL::HMAC.hexdigest()`'s [one shot interface](https://ruby-doc.org/stdlib-2.5.1/libdoc/openssl/rdoc/OpenSSL/HMAC.html#class-OpenSSL::HMAC-label-HMAC-SHA256+using+one-shot+interface) directly for `md5`, `sha1`, `sha256`, and `sha512`, and fall back to the old Digest module for the normal `md5hash`:

```
# `value` being just a string in the "&key=value" format we used
# Also keep in mind md5hash must have the secrect directly appended, _not_ appended with a leading "&"
Digest::MD5.hexdigest "#{value}#{@secret}"
```

If we craft a string for our parameters instead of using the digest, it makes it easier to re-use that value.

If you want, ping me on Slack in the morning and we can screenshare.

2019-11-06 15:12 UTC, benhayehudi commented
Hey, @timcraft!

I had a productive screenshare with @dragonmantank where we addressed the hashing issue, and got it to conform. Whenever you have a spare moment for a code review again, would be great.

Have a good night,

Ben

2019-11-07 10:40 UTC, timcraft commented
> Michael's out of the office this week but I can change the repo settings if that would be helpful? It looks like the default branch is `master` so I'm not sure what is needed here

@lornajane Okay thanks, it's not urgent. Maybe better to leave it if the other repos are the same (?), I was just thinking if the default branch was set to `develop` then that would match the workflow that we're currently using, and prevent anything from accidentally being merged into master.

2019-11-07 10:40 UTC, timcraft commented
> I had a productive screenshare with @dragonmantank where we addressed the hashing issue, and got it to conform. Whenever you have a spare moment for a code review again, would be great.

Excellent, thanks. Leave it with me and I'll get it in the next release.

2019-11-07 11:08 UTC, lornajane commented
> > Michael's out of the office this week but I can change the repo settings if that would be helpful? It looks like the default branch is `master` so I'm not sure what is needed here
> 
> @lornajane Okay thanks, it's not urgent. Maybe better to leave it if the other repos are the same (?), I was just thinking if the default branch was set to `develop` then that would match the workflow that we're currently using, and prevent anything from accidentally being merged into master.

The other repos all use more of a GitHub flow than a git flow, so they have `master` as default rather than `develop`. However I can't see a reason why all the libraries should be forced to follow the same convention so if you'd like the branch changing and you have clear `CONTRIBUTING` instructions, we can do that.

2019-11-12 10:59 UTC, timcraft requested changes
Just to double check: the signatures generated by Nexmo for incoming messages are all uppercase? The [NDP guide](https://developer.nexmo.com/concepts/guides/signing-messages) doesn't mention upcasing for the signature generation.

2019-11-12 10:59 UTC, timcraft commented on lib/nexmo/signature.rb
> +        v.gsub(/[&_]/, '')
This line appears to be unnecessary, no idea what it's meant to be doing?

2019-11-12 10:59 UTC, timcraft commented on lib/nexmo/signature.rb
> +        digest = OpenSSL::HMAC.hexdigest(signature_method, @secret, digest_string).upcase
These two `digest` variable assignments are unnecessary.

2019-11-12 10:59 UTC, timcraft commented on lib/nexmo/signature.rb
> +require 'digest'
Minor thing, but if you change this back to `digest/md5` it'll make it easier to see what's actually changed—openssl is the one being added, digest/md5 is already being used (and continues to be used).

2019-11-12 15:33 UTC, dragonmantank commented on lib/nexmo/signature.rb
> +        v.gsub(/[&_]/, '')
This should actually be
```
v.gsub(/[&=]/, '_')
```
You have to convert any `&` or `=` characters in the values to `_`.  See https://developer.nexmo.com/concepts/guides/signing-messages#manually-generate-a-signature

2019-11-12 15:57 UTC, dragonmantank commented
> Just to double check: the signatures generated by Nexmo for incoming messages are all uppercase? The [NDP guide](https://developer.nexmo.com/concepts/guides/signing-messages) doesn't mention upcasing for the signature generation.

[We explicitly do this in the PHP SDK](https://github.com/Nexmo/nexmo-php/blob/2d352e982cf09d2b5b14f1959da0b061f337f24a/src/Client/Signature.php#L71), so ported it here so that we could make the tests match. Playing with the code snippets, when sending with a signature the casing does not actually matter, you can send it upper or lower.

In the PHP SDK [we translate both to lowercase to check an incoming signature](https://github.com/Nexmo/nexmo-php/blob/2d352e982cf09d2b5b14f1959da0b061f337f24a/src/Client/Signature.php#L130), so at the very least I'm guessing we cannot guarantee that it is always lower or upper when receiving (though getting signed messages is an account thing, so I have no idea how many customers actually use it).

2019-11-14 10:58 UTC, timcraft commented on lib/nexmo/signature.rb
> +        v.gsub(/[&_]/, '')
Even with the correct substitutions that line isn't doing anything because the return value isn't used—the following line which appends to `digest_string` is just using the original value. 

Given tests aren't failing I'd suggest adding a test to cover the substitution behaviour. I'd also suggest using [String#tr](https://ruby-doc.org/core-2.6.5/String.html#method-i-tr) instead of #gsub, but at a minimum it needs changes a) to perform the correct substitutions and b) to use the return value.

2019-11-14 11:05 UTC, timcraft commented
> [We explicitly do this in the PHP SDK](https://github.com/Nexmo/nexmo-php/blob/2d352e982cf09d2b5b14f1959da0b061f337f24a/src/Client/Signature.php#L71), so ported it here so that we could make the tests match. Playing with the code snippets, when sending with a signature the casing does not actually matter, you can send it upper or lower.

I like the idea of making the tests match, but upcasing/downcasing seems a bit redundant if it's not strictly necessary. Ruby SDK only supports checking incoming signatures currently, I'll see if I can confirm whether signed messages are uppercase or lowercase. Not a blocker for this anyway.

2019-11-14 11:20 UTC, mheap commented
Paging @lornajane who has the details on this

2019-11-14 17:44 UTC, benhayehudi commented on lib/nexmo/signature.rb
> +        v.gsub(/[&_]/, '')
Hi, @timcraft. Thanks for suggesting `#tr`. I explored the differentiations and distinctions, and I believe you are correct, that it is a more accurate method to use for our use case. I will make that adjustment. I'm not sure how our tests are still passing if the value is not being passed into `digest_string` correctly. A closer look does indeed show that I am not passing in the modified value into `digest_string`, I will adjust that as well.

2019-11-15 15:41 UTC, benhayehudi commented on lib/nexmo/signature.rb
> +        v.gsub(/[&_]/, '')
Hey @timcraft, Would appreciate your thoughts on the commit I just added. I thought more about your suggestion to test the string substitution behavior, and since it was not performing correctly even while the current tests passed, I went ahead and added a test to specifically check that functionality. In order to do so, I split up the functionality of `#digest` into two separate methods; one that performs the string composition, including substitution, and the other that performs the actual digest.

2019-11-18 11:41 UTC, merged