DEVX-3607 Replace JWT generation with Nexmo Ruby JWT generator
Vonage/vonage-ruby-sdk pull request #166
Opened 2020-07-20 06:41 UTC by bencgreenberg

This PR fulfills DEVX-3607 to replace the JWT generation in the SDK with the [Nexmo Ruby JWT](https://github.com/Nexmo/nexmo-jwt-ruby) generator.

2020-07-20 10:56 UTC, mheap requested changes
Can we also have a test when `ttl` is passed? I know it's part of the JWT lib tests, but it's also a part of the SDKs public API as we expose it through `Nexmo::JWT`

I'd also like to see `Time.now` mocked and a complete JWT string comparison done as the tests here don't validate that the generated JWT is valid

2020-07-22 11:01 UTC, mheap commented on lib/nexmo/jwt.rb
> +      payload[:private_key] = private_key unless payload[:private_key]
Should this be `if private_key && !payload[:private_key]`?

2020-07-22 11:06 UTC, bencgreenberg commented on lib/nexmo/jwt.rb
> +      payload[:private_key] = private_key unless payload[:private_key]
You're right! What about also adding a `raise` as well if neither are present?

2020-07-23 10:08 UTC, mheap requested changes

2020-07-23 10:08 UTC, mheap commented on lib/nexmo/jwt.rb
> +      raise "Expecting 'private_key' in either the payload or as a separate parameter" if !payload[:private_key] && !private_key
Missing a test for this branch

2020-07-23 10:41 UTC, bencgreenberg commented on lib/nexmo/jwt.rb
> +      raise "Expecting 'private_key' in either the payload or as a separate parameter" if !payload[:private_key] && !private_key
Good catch!

2020-07-23 16:29 UTC, merged