Migration to Vonage
Vonage/vonage-ruby-sdk pull request #174
Opened 2020-08-13 11:36 UTC by bencgreenberg

2020-09-03 12:19 UTC, kellyjandrews commented on LICENSE.txt
> +
Add `Copyright 2020 Vonage`

2020-09-03 12:46 UTC, kellyjandrews requested changes
Also make sure to change https://github.com/Vonage/vonage-ruby-sdk/pull/174/commits/f7964b08ace33a8d479637cae1c8209f015c7eaf#diff-04c6e90faac2675aa89e2176d2eec7d8R188 to Apache 2.0

2020-09-03 12:46 UTC, kellyjandrews commented on test/vonage/test.rb
> +  add_filter 'test/Vonage'
Is the capitalization here accurate?

2020-09-03 12:46 UTC, kellyjandrews commented on test/vonage/test.rb
> +      'Vonage-signature-secret'
Check capitalization here.

2020-09-03 12:46 UTC, kellyjandrews commented on CHANGES.md
> +# 8.0.0
This needs updated if you changed the version back to 7.2.0

2020-09-03 12:46 UTC, kellyjandrews commented on vonage.gemspec
> +  s.license = 'MIT'
Change license

2020-09-03 12:46 UTC, kellyjandrews commented on vonage.gemspec
> +  s.email = ['devrel@nexmo.com']
devrel@vonage.com

2020-09-03 14:12 UTC, kellyjandrews commented on LICENSE.txt
> +
I see it at the bottom now :)

2020-09-03 14:43 UTC, kellyjandrews requested changes
Update to Server SDK where applicable.

2020-09-03 14:43 UTC, kellyjandrews commented on README.md
> +# Vonage Client Library for Ruby
Vonage Server SDK for Ruby

2020-09-03 14:43 UTC, kellyjandrews commented on README.md
>  To install the Ruby client library using Rubygems:
Ruby Server SDK

2020-09-03 14:43 UTC, kellyjandrews commented on vonage.gemspec
> +  s.description = 'Vonage Client Library for Ruby'
Server SDK

2020-09-03 14:43 UTC, kellyjandrews commented on vonage.gemspec
> +  s.summary = 'This is the Ruby client library for Vonage APIs. To use it you\'ll need a Vonage account. Sign up for free at https://www.vonage.com'
Server SDK

2020-09-03 14:43 UTC, kellyjandrews commented on README.md
> +This is the Ruby client library for Vonage APIs. To use it you'll
Ruby Server SDK

2020-09-07 07:26 UTC, bencgreenberg commented on test/vonage/test.rb
> +      'Vonage-signature-secret'
I'm going to leave it as it is, since I used the new secret string `Vonage-signature-secret` to generate a test JWT for the tests. It only impacts the tests and has no implications for users.

2020-09-08 13:14 UTC, superdiana approved these changes
LGTM. Kelly's review was amazing.

2020-09-08 13:21 UTC, slorello89 requested changes
Couple minor questions about sorbet, versioning, and a couple of things that look like they may be outside of the scope of this review.

2020-09-08 13:21 UTC, slorello89 commented on Gemfile
> +gem 'sorbet-runtime'
Did soemething change where `sorbet-runtime` is now required?

2020-09-08 13:21 UTC, slorello89 commented on lib/vonage/logger.rb
> +# typed: strict
This seems like it's outside the scope of this PR

2020-09-08 13:21 UTC, slorello89 commented on lib/vonage/version.rb
>    VERSION = '7.2.0'
This should probably be iterated to 7.3.0 for the first version of the Vonage ruby package. Is that separate from this PR?

2020-09-08 13:21 UTC, slorello89 commented on sorbet/rbi/gems/addressable.rbi
> +# typed: strict
move from strong -> strict in these files - is that part of the CI process or is it something unrelated to this PR?

2020-09-08 13:21 UTC, slorello89 commented on sorbet/rbi/gems/timecop.rbi
> +# This file is autogenerated. Do not edit it by hand. Regenerate it with:
Is this a new dependency?

2020-09-08 13:21 UTC, slorello89 commented on sorbet/rbi/gems/nexmo-jwt.rbi
> +# This file is autogenerated. Do not edit it by hand. Regenerate it with:
bunch of stuff being pulled in under `sorbet/rbi/gems` - was this intentional? shouldn't this be pulled from the package managers and have this stuff `git ignored`?

2020-09-08 13:21 UTC, slorello89 commented on sorbet/rbi/todo.rbi
> +module ::Rails; end
is rails a new dependency?

2020-09-08 13:21 UTC, slorello89 commented on lib/vonage/conversations.rb
> +module Vonage
Is conversations supposed to be in here?

2020-09-08 13:32 UTC, bencgreenberg commented on lib/vonage/version.rb
>    VERSION = '7.2.0'
I checked with @mheap on this, and he asked that the version stay the same.

2020-09-08 13:33 UTC, bencgreenberg commented on sorbet/rbi/gems/addressable.rbi
> +# typed: strict
There were some breaking issues in sorbet a while back that were broken, as part of fixing it overall in the SDK, it reran the auto sigil generator again, and moved some of these, in this case, it's a rbi file for an external library, has no impact.

2020-09-08 13:33 UTC, bencgreenberg commented on sorbet/rbi/gems/timecop.rbi
> +# This file is autogenerated. Do not edit it by hand. Regenerate it with:
Already integrated from an earlier version

2020-09-08 13:34 UTC, bencgreenberg commented on sorbet/rbi/todo.rbi
> +module ::Rails; end
All part of ongoing changes to Sorbet underlying, not to worry about here

2020-09-08 13:34 UTC, bencgreenberg commented on lib/vonage/conversations.rb
> +module Vonage
It's not typed yet, so yes

2020-09-08 13:35 UTC, bencgreenberg commented on sorbet/rbi/gems/nexmo-jwt.rbi
> +# This file is autogenerated. Do not edit it by hand. Regenerate it with:
The JWT library is not typed, so there is no definition to pull from, it needs to be here as such

2020-09-08 13:36 UTC, bencgreenberg commented on lib/vonage/logger.rb
> +# typed: strict
It was strict previously, there was a major issue with Sorbet, it was resolved, bringing it back. No underlying changes.

2020-09-08 13:36 UTC, bencgreenberg commented on Gemfile
> +gem 'sorbet-runtime'
Yes, Sorbet had some changes.

2020-09-08 14:28 UTC, kellyjandrews approved these changes
LGTM

2020-09-08 14:53 UTC, bencgreenberg commented
Thanks, everyone for the reviews! I'm going to do one more run of all the functionality tomorrow one last time in the renamed classes just to satisfy my over-protective style, and then I'll go ahead and merge and release.

2020-09-09 07:04 UTC, merged