Add sorbet types to some modules
Vonage/vonage-ruby-sdk pull request #180
Opened 2020-10-12 16:15 UTC by ohbarye

@bencgreenberg 
Thanks for giving me a chance to contribute.
I'm so new to Sorbet, please let me know if this change has anything wrong.

## Issue

Part of https://github.com/Vonage/vonage-ruby-sdk/issues/178

## Changes

Added Sorbet typings to the modules below.

- `Vonage::UserAgent`
- `Vonage::GSM7`

2020-10-12 18:18 UTC, bencgreenberg commented
Hey @ohbarye, so glad to see your PR on this! I'll take a look this week. Thanks for contributing!

2020-10-14 19:22 UTC, bencgreenberg commented on lib/vonage/gsm7.rb
> +    sig {params(string: T.nilable(String)).returns(T.nilable(Integer))}
```suggestion
    sig { params(string: T.nilable(String)).returns(T.nilable(Integer)) }
```

2020-10-14 19:22 UTC, bencgreenberg commented on lib/vonage/gsm7.rb
> +    extend T::Sig
```suggestion
    extend T::Sig
    
```

2020-10-14 19:25 UTC, bencgreenberg requested changes
This looks great, @ohbarye! I've left just a couple small suggestions to incorporate.

2020-10-15 14:06 UTC, ohbarye commented
@bencgreenberg Thanks for your review, I've addressed them.

2020-10-16 12:36 UTC, bencgreenberg commented
LGTM 👍

2020-10-16 12:36 UTC, bencgreenberg approved these changes

2020-10-16 12:36 UTC, merged