Adding Video Functionality
Vonage/vonage-ruby-sdk pull request #249
Opened 2022-10-04 14:50 UTC by superchilled

2022-12-01 14:31 UTC, dragonmantank requested changes
Couple of changes to creating sessions and archives

2022-12-01 14:31 UTC, dragonmantank commented on lib/vonage/video.rb
> +    #     p2p_preference: 'disabled'
We don't actually expose this through the SDKs, but instead expose `mediaMode`, which is either `routed` or `relayed`. This then swaps `p2p_preference` to `disabled` or `enabled`, respectively, under the hood.

2022-12-01 14:31 UTC, dragonmantank commented on lib/vonage/video.rb
> +      response
This is another oddity of creating a session - we don't return the full response in the SDKs. We only return:

* `sessionId`
* `archiveMode`
* `mediaMode`
* `location`

2022-12-01 14:31 UTC, dragonmantank commented on lib/vonage/video.rb
> +    def generate_client_token(session_id:, application_id: @config.application_id, private_key: @config.private_key, scope: 'session.connect', role: 'publisher', **params)
Why are we asking the dev to pass in the private key? Shouldn't this already be a part of their auth that we can pull this out of?

If users want to make just a general JWT, they should sue the JWT library directly.

2022-12-01 14:31 UTC, dragonmantank commented on lib/vonage/video/archives.rb
> +    # Create a new archive.
We need to make sure we support the newer multiArchive tag

2022-12-08 12:27 UTC, superchilled commented on lib/vonage/video.rb
> +    #     p2p_preference: 'disabled'
I've updated the logic for this and added some tests to cover the new logic.

2022-12-08 12:28 UTC, superchilled commented on lib/vonage/video.rb
> +      response
[As above](https://github.com/Vonage/vonage-ruby-sdk/pull/249#discussion_r1043298268)

2022-12-08 12:44 UTC, superchilled commented on lib/vonage/video.rb
> +    def generate_client_token(session_id:, application_id: @config.application_id, private_key: @config.private_key, scope: 'session.connect', role: 'publisher', **params)
> Shouldn't this already be a part of their auth that we can pull this out of?

Yeah, it should be set in the `Config` object, and I do set the default value for the param as `@config.private_key`, though I guess the question is whether we need to even expose this param at all (same goes for `application_id`). I think I was just following the same logic that already exists in the [JWT.generate](https://github.com/Vonage/vonage-ruby-sdk/blob/5dd438f058cbffa7bb92caccf0ed703b40a011ea/lib/vonage/jwt.rb#L36) method signature, though I'm now wondering why it's even exposed there.

Will update the method sig.

2022-12-08 12:59 UTC, superchilled commented on lib/vonage/video/archives.rb
> +    # Create a new archive.
Updated the code comments.

2022-12-08 15:09 UTC, dragonmantank approved these changes
LGTM

2022-12-12 12:01 UTC, superchilled commented
Closing the PR as not merging into `dev` yet, but instead releasing a `beta` version of the library.

2022-12-12 12:01 UTC, closed without merging