DEVX-7907: Update Verify2 Silent Authentication workflow options
Vonage/vonage-ruby-sdk pull request #300
Opened 2023-12-03 13:56 UTC by superchilled

2023-12-06 14:31 UTC, SecondeJK requested changes
possible changes, def not essential

2023-12-06 14:31 UTC, SecondeJK commented on lib/vonage/verify2/channels/silent_auth.rb
> +    def initialize(to:, redirect_url: nil, sandbox: false)
Sandbox defaults to false internally within the API - can we leave it to not be set at all in the request if the user sets nothing? I think that might be cleaner/more explicit

2023-12-06 14:31 UTC, SecondeJK commented on lib/vonage/verify2/channels/silent_auth.rb
> +      self.redirect_url = redirect_url if redirect_url
could possibly give the user a bit more defence here by checking that it's a valid url pattern?

2023-12-06 14:53 UTC, superchilled commented on lib/vonage/verify2/channels/silent_auth.rb
> +    def initialize(to:, redirect_url: nil, sandbox: false)
Yeah, I could use a similar pattern to what I've used for `redirect_url`, e.g.

```ruby
def initialize(to:, redirect_url: nil, sandbox: nil
  self.sandbox = sandbox if [true, false].include? sandbox
  # rest of code
end
```

It kinda duplicates the code I have for validation in the `sandbox=` setter, but I guess that's ok.

2023-12-06 14:55 UTC, superchilled commented on lib/vonage/verify2/channels/silent_auth.rb
> +      self.redirect_url = redirect_url if redirect_url
I'd have to use a Regex, which I'm always a bit wary of as I always find them either too broad or to narrow. For example, something like this `/\A#{URI::regexp}\z/` would allow any valid URL, but do we want to constrain it to certain schemes? (e.g. just `http` or `https`)?

2023-12-06 14:59 UTC, SecondeJK commented on lib/vonage/verify2/channels/silent_auth.rb
> +      self.redirect_url = redirect_url if redirect_url
Ah in that case scrap it. Some languages have some basic url base functions to check IIRC but if it's a hassle let's leave it

2023-12-06 15:55 UTC, superchilled commented on lib/vonage/verify2/channels/silent_auth.rb
> +      self.redirect_url = redirect_url if redirect_url
Ruby does have a URI parser that I could use to do some very *basic* checking. Something like:

```ruby
uri = URI.parse(url)
if uri.is_a?(URI::HTTP)
  # do stuff
else
  # do other stuff
end
```

Users could still potentially pass in a value that would then be rejected by the API, but I guess it's better so have *some* level of validation then none at all. I'll add something in, and put in some basic tests.

2023-12-07 16:35 UTC, superchilled commented on lib/vonage/verify2/channels/silent_auth.rb
> +    def initialize(to:, redirect_url: nil, sandbox: false)
Resolved in https://github.com/Vonage/vonage-ruby-sdk/pull/300/commits/d3ffd543975de0aee0e98418a185f58fa0168a4a

2023-12-07 16:35 UTC, superchilled commented on lib/vonage/verify2/channels/silent_auth.rb
> +      self.redirect_url = redirect_url if redirect_url
Resolved in https://github.com/Vonage/vonage-ruby-sdk/pull/300/commits/d3ffd543975de0aee0e98418a185f58fa0168a4a

2023-12-07 21:37 UTC, SecondeJK approved these changes

2023-12-08 11:06 UTC, merged